spring:
  application:
    name: Hackathon De 01
  ai:
    openai:
      api-key: ${OPENAI_API_KEY}
      base-url: ${OPENAI_BASE_URL}
      chat:
        model: ${OPENAI_MODEL}
        temperature: 0.3
      embedding:
        model: text-embedding-3-small
    vectorstore:
      pgvector:
        initialize-schema: true
        dimensions: 1536
        index-type: hnsw
        distance-type: cosine_distance
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://aws-0-ap-northeast-1.pooler.supabase.com:6543/postgres
    username: ${USERNAME_SUPABASE}
    password: ${PASSWORD_SUPABASE}
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
